---
params:
  - name:
      required: true
  - version:
      required: true
      default: "1.0.0"
  - description
  - author
text: |
  {
    "name": "{{=it.name}}"
    , "version": "{{=it.version}}"
    {{? it.description }}
    , "description": "{{=it.description}}"
    {{?}}
    {{? it.author }}
    , "author": "{{=it.author}}"
    {{?}}
  }
