---
params:

  string:
  stringR:
    required: true
  stringN:
    default:
  stringD:
    default: Default
  stringT:
    type: string
  stringRD:
    required: true
    default: Default
  stringRT:
    required: true
    type: string
  stringDT:
    default: Default
    type: string
  stringRDT:
    required: true
    default: Default
    type: string

  intT:
    type: int
  intRT:
    required: true
    type: int
  intNT:
    default:
    type: int
  intDT:
    default: 1
    type: int
  intRDT:
    required: true
    default: 1
    type: int

  floatT:
    type: float
  floatRT:
    required: true
    type: float
  floatNT:
    default:
    type: float
  floatDT:
    default: 1.1
    type: float
  floatRDT:
    required: true
    default: 1.1
    type: float

  boolT:
    type: bool
  boolRT:
    required: true
    type: bool
  boolNT:
    default:
    type: bool
  boolDT:
    default: true
    type: bool
  boolRDT:
    required: true
    default: true
    type: bool

  arrayST:
    type: array<string>
  arraySRT:
    required: true
    type: array<string>
  arraySNT:
    default:
    type: array<string>
  arraySDT:
    default:
      - one
    type: array<string>
  arraySRDT:
    required: true
    default:
      - one
    type: array<string>

  arrayIT:
    type: array<int>
  arrayIRT:
    required: true
    type: array<int>
  arrayINT:
    default:
    type: array<int>
  arrayIDT:
    default:
      - 1
    type: array<int>
  arrayIRDT:
    required: true
    default:
      - 1
    type: array<int>

  arrayFT:
    type: array<float>
  arrayFRT:
    required: true
    type: array<float>
  arrayFNT:
    default:
    type: array<float>
  arrayFDT:
    default:
      - 1.1
    type: array<float>
  arrayFRDT:
    required: true
    default:
      - 1.1
    type: array<float>

  arrayBT:
    type: array<bool>
  arrayBRT:
    required: true
    type: array<bool>
  arrayBNT:
    default:
    type: array<bool>
  arrayBDT:
    default:
      - true
    type: array<bool>
  arrayBRDT:
    required: true
    default:
      - true
    type: array<bool>
text: |
  Params test
  {{=JSON.stringify(it, null, 2)}}
